### PR TITLE
Fix selection bugs

### LINKED ISSUE #12: Selection bugs
To reproduce:
- visit https://dreamy-swirles-5330b3.netlify.com/
- mouse click on an available day that is not the 1st available day
- click on the 1st available day
- observe that you can't select it

And a related keyboard bug:
- visit https://dreamy-swirles-5330b3.netlify.com/
- use the arrow keys to move the focus outline to an unavailable day in the future
- press spacebar
- observe that you are able to select an unavailable day

### PR DESCRIPTION
**Pull request by smcmurtry**
Fixes #12. An old version of `isBlockedDay` was getting called by mistake. So I could call the user provided `isBlockedDay` function in src/scheduler/Calendar/_util.js, I removed the default state argument. But I am not sure what it was for - @timarney can you let me know if this fix makes sense?

### CODE REVIEW

File: src/scheduler/Calendar/_util.js [hunk 1]
```diff
@@ -1,17 +1,9 @@
 import dayjs from "dayjs";
 
-const blockedDay = (day, state) => {
```
Comment (smcmurtry) [inline src/scheduler/Calendar/_util.js:3]: This is the old function that was getting called by mistake.

File: src/scheduler/App.js [hunk 2]
```diff
@@ -13,10 +13,7 @@ export const App = () => {
 
   options = { init: setIntialState, ...window.schedulerOptions };
 
-  const providerState = options.init({
-    dayjs,
-    defaultState: defaultState()
```
Comment (smcmurtry) [inline src/scheduler/App.js]: This arg doesn't seem to be doing anything, at least for my use case

Comment (timarney) [reply src/scheduler/App.js]: The idea here was to provide a default state so the end user only needs to override "custom" options.  This will vary but I would like to keep this i.e for cases where you only want to change one thing.
```
{...defaultState, yourState}
```

Also if the end user forgets to set a "required" piece of state that could cause issues.

**Comment by smcmurtry** [comment]
Okay I got some help from @brdunfield and now this PR should be ready to go. @timarney mind taking another look?

File: src/scheduler/store.js [hunk 3]
```diff
@@ -93,7 +99,7 @@ export const StateProvider = ({ value, children }) => {
         newState = { ...state, time_values: action.payload };
         break;
       case "SELECT_DATE":
-        if (isBlockedDay(dayjs(action.payload), state)) {
+        if (mergedState.isBlockedDay(dayjs(action.payload))) {
```
Comment (timarney) [inline src/scheduler/store.js]: This should use state.isBlockedDay as that param would be the current state.
